<?php

namespace Database\Seeders;

use App\Models\ProductDetail;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $product=[[
            'user_id'=>'3',
            'product_name'=>'GMK Frost Switch',
            'folderpath'=>'img/productseederimg1',
            'owner'=>'adrian123',
            'shortdesc'=>'This is product 1',
            'product_type'=>'customkeyboard',
            'productlist'=>'red switch',
            'moq'=>'1',
            'productstock'=>'10',
            'productprice'=>'3000000',
            'startdate'=>'2022-06-13',
            'enddate'=>'2022-12-13',
            'enddategb'=>'2023-12-13',
            'endtime'=>'18:06',
            'shippingdate'=>'2023-06-13',
            'discordlink'=>'https://discord.gg/',
            'deleted'=>'0',
            'verified'=>'1',
            'rejectreason'=>'0',
            'interestdone'=>'0',
            'isfinish'=>'0',
            'icfail'=>'0',


        ],
      [
        'user_id'=>'3',
        'product_name'=>'Keychron Q1',
        'folderpath'=>'img/productseederimg2',
        'owner'=>'adrian123',
        'shortdesc'=>'This is product 2',
        'product_type'=>'customkeyboard',
        'productlist'=>'red switch',
        'moq'=>'1',
        'productstock'=>'10',
        'productprice'=>'3100000',
        'startdate'=>'2022-06-13',
        'enddate'=>'2022-12-13',
        'enddategb'=>'2023-12-13',
        'endtime'=>'18:06',
        'shippingdate'=>'2023-06-13',
        'discordlink'=>'https://discord.gg/',
        'deleted'=>'0',
        'verified'=>'1',
        'rejectreason'=>'0',
        'interestdone'=>'0',
        'isfinish'=>'0',
        'icfail'=>'0',

        ],
      [
        'user_id'=>'3',
        'product_name'=>'QK65',
        'folderpath'=>'img/productseederimg3',
        'owner'=>'adrian123',
        'shortdesc'=>'This is product 3',
        'product_type'=>'customkeyboard',
        'productlist'=>'red switch',
        'moq'=>'1',
        'productstock'=>'10',
        'productprice'=>'2800000',
        'startdate'=>'2022-06-13',
        'enddate'=>'2022-12-13',
        'enddategb'=>'2023-12-13',
        'endtime'=>'18:06',
        'shippingdate'=>'2023-06-13',
        'discordlink'=>'https://discord.gg/',
        'deleted'=>'0',
        'verified'=>'1',
        'rejectreason'=>'0',
        'interestdone'=>'0',
        'isfinish'=>'0',
        'icfail'=>'0',

        ],

        [
          'user_id'=>'3',
          'product_name'=>'Shurikey Matrix-01',
          'folderpath'=>'img/productseederimg4',
          'owner'=>'adrian123',
          'shortdesc'=>'Therefore we have decided to do another round for it with almost completely redesigned novelties and bring it to intl as well. After comprehensive consideration, we decided to cooperate with SHURIKEY this time.',
          'product_type'=>'customkeyboard',
          'productlist'=>'red switch',
          'moq'=>'1',
          'productstock'=>'10',
          'productprice'=>'2800000',
          'startdate'=>'2022-06-13',
          'enddate'=>'2022-12-13',
          'enddategb'=>'2023-12-13',
          'endtime'=>'18:06',
          'shippingdate'=>'2023-06-13',
          'discordlink'=>'https://discord.gg/',
          'deleted'=>'0',
          'verified'=>'1',
          'rejectreason'=>'0',
          'interestdone'=>'0',
          'isfinish'=>'0',
          'icfail'=>'0',
  
          ],
 

          [
            'user_id'=>'3',
            'product_name'=>'Cherry Taro',
            'folderpath'=>'img/productseederimg5',
            'owner'=>'adrian123',
            'shortdesc'=>'Cherry PBT Dyesub Keycaps.',
            'product_type'=>'customkeyboard',
            'productlist'=>'Base Kit',
            'moq'=>'1',
            'productstock'=>'10',
            'productprice'=>'2300000',
            'startdate'=>'2022-06-13',
            'enddate'=>'2022-12-13',
            'enddategb'=>'2023-12-13',
            'endtime'=>'18:06',
            'shippingdate'=>'2023-06-13',
            'discordlink'=>'https://discord.gg/',
            'deleted'=>'0',
            'verified'=>'1',
            'rejectreason'=>'0',
            'interestdone'=>'0',
            'isfinish'=>'0',
            'icfail'=>'0',
    
            ],

            [
              'user_id'=>'3',
              'product_name'=>'GMK Serika 2',
              'folderpath'=>'img/productseederimg6',
              'owner'=>'adrian123',
              'shortdesc'=>'Cherry ABS Double-Shot Keycaps.',
              'product_type'=>'customkeyboard',
              'productlist'=>'Base Kit',
              'moq'=>'1',
              'productstock'=>'10',
              'productprice'=>'3000000',
              'startdate'=>'2022-06-13',
              'enddate'=>'2022-12-13',
              'enddategb'=>'2023-12-13',
              'endtime'=>'18:06',
              'shippingdate'=>'2023-06-13',
              'discordlink'=>'https://discord.gg/',
              'deleted'=>'0',
              'verified'=>'1',
              'rejectreason'=>'0',
              'interestdone'=>'0',
              'isfinish'=>'0',
              'icfail'=>'0',
      
              ],

    
                [
                  'user_id'=>'3',
                  'product_name'=>'GMK Yuri',
                  'folderpath'=>'img/productseederimg7',
                  'owner'=>'adrian123',
                  'shortdesc'=>'Cherry ABS Double-Shot Keycaps.',
                  'product_type'=>'customkeyboard',
                  'productlist'=>'Base Kit',
                  'moq'=>'1',
                  'productstock'=>'10',
                  'productprice'=>'3100000',
                  'startdate'=>'2022-06-13',
                  'enddate'=>'2022-12-13',
                  'enddategb'=>'2023-12-13',
                  'endtime'=>'18:06',
                  'shippingdate'=>'2023-06-13',
                  'discordlink'=>'https://discord.gg/',
                  'deleted'=>'0',
                  'verified'=>'1',
                  'rejectreason'=>'0',
                  'interestdone'=>'0',
                  'isfinish'=>'0',
                  'icfail'=>'0',
          
                  ],

                  [
                    'user_id'=>'3',
                    'product_name'=>'GMK Honor Light',
                    'folderpath'=>'img/productseederimg8',
                    'owner'=>'adrian123',
                    'shortdesc'=>'Cherry ABS Double-Shot Keycaps.',
                    'product_type'=>'customkeyboard',
                    'productlist'=>'Base Kit',
                    'moq'=>'1',
                    'productstock'=>'10',
                    'productprice'=>'3200000',
                    'startdate'=>'2022-06-13',
                    'enddate'=>'2022-12-13',
                    'enddategb'=>'2023-12-13',
                    'endtime'=>'18:06',
                    'shippingdate'=>'2023-06-13',
                    'discordlink'=>'https://discord.gg/',
                    'deleted'=>'0',
                    'verified'=>'1',
                    'rejectreason'=>'0',
                    'interestdone'=>'0',
                    'isfinish'=>'0',
                    'icfail'=>'0',
            
                    ],

                    [
                      'user_id'=>'3',
                      'product_name'=>'GMK Honor Dark',
                      'folderpath'=>'img/productseederimg9',
                      'owner'=>'adrian123',
                      'shortdesc'=>'Cherry ABS Double-Shot Keycaps.',
                      'product_type'=>'customkeyboard',
                      'productlist'=>'Base Kit',
                      'moq'=>'1',
                      'productstock'=>'10',
                      'productprice'=>'3200000',
                      'startdate'=>'2022-06-13',
                      'enddate'=>'2022-12-13',
                      'enddategb'=>'2023-12-13',
                      'endtime'=>'18:06',
                      'shippingdate'=>'2023-06-13',
                      'discordlink'=>'https://discord.gg/',
                      'deleted'=>'0',
                      'verified'=>'1',
                      'rejectreason'=>'0',
                      'interestdone'=>'0',
                      'isfinish'=>'0',
                      'icfail'=>'0',
              
                      ],

                      [
                        'user_id'=>'3',
                        'product_name'=>'GMK Mudbeam',
                        'folderpath'=>'img/productseederimg10',
                        'owner'=>'adrian123',
                        'shortdesc'=>'Cherry ABS Double-Shot Keycaps.',
                        'product_type'=>'customkeyboard',
                        'productlist'=>'Base Kit',
                        'moq'=>'1',
                        'productstock'=>'10',
                        'productprice'=>'3000000',
                        'startdate'=>'2022-06-13',
                        'enddate'=>'2022-12-13',
                        'enddategb'=>'2023-12-13',
                        'endtime'=>'18:06',
                        'shippingdate'=>'2023-06-13',
                        'discordlink'=>'https://discord.gg/',
                        'deleted'=>'0',
                        'verified'=>'1',
                        'rejectreason'=>'0',
                        'interestdone'=>'0',
                        'isfinish'=>'0',
                        'icfail'=>'0',
                
                        ],

                        [
                          'user_id'=>'3',
                          'product_name'=>'GMK Bento',
                          'folderpath'=>'img/productseederimg11',
                          'owner'=>'adrian123',
                          'shortdesc'=>'Cherry ABS Double-Shot Keycaps.',
                          'product_type'=>'customkeyboard',
                          'productlist'=>'Base Kit',
                          'moq'=>'1',
                          'productstock'=>'10',
                          'productprice'=>'3500000',
                          'startdate'=>'2022-06-13',
                          'enddate'=>'2022-12-13',
                          'enddategb'=>'2023-12-13',
                          'endtime'=>'18:06',
                          'shippingdate'=>'2023-06-13',
                          'discordlink'=>'https://discord.gg/',
                          'deleted'=>'0',
                          'verified'=>'1',
                          'rejectreason'=>'0',
                          'interestdone'=>'0',
                          'isfinish'=>'0',
                          'icfail'=>'0',
                  
                          ],

                          [
                            'user_id'=>'3',
                            'product_name'=>'GMK Grand Prix',
                            'folderpath'=>'img/productseederimg12',
                            'owner'=>'adrian123',
                            'shortdesc'=>'Cherry ABS Double-Shot Keycaps.',
                            'product_type'=>'customkeyboard',
                            'productlist'=>'Base Kit',
                            'moq'=>'1',
                            'productstock'=>'10',
                            'productprice'=>'3300000',
                            'startdate'=>'2022-06-13',
                            'enddate'=>'2022-12-13',
                            'enddategb'=>'2023-12-13',
                            'endtime'=>'18:06',
                            'shippingdate'=>'2023-06-13',
                            'discordlink'=>'https://discord.gg/',
                            'deleted'=>'0',
                            'verified'=>'1',
                            'rejectreason'=>'0',
                            'interestdone'=>'0',
                            'isfinish'=>'0',
                            'icfail'=>'0',
                    
                            ],

                            [
                              'user_id'=>'3',
                              'product_name'=>'GMK Space Cadet II',
                              'folderpath'=>'img/productseederimg13',
                              'owner'=>'adrian123',
                              'shortdesc'=>'Cherry ABS Double-Shot Keycaps.',
                              'product_type'=>'customkeyboard',
                              'productlist'=>'Base Kit',
                              'moq'=>'1',
                              'productstock'=>'10',
                              'productprice'=>'3000000',
                              'startdate'=>'2022-06-13',
                              'enddate'=>'2022-12-13',
                              'enddategb'=>'2023-12-13',
                              'endtime'=>'18:06',
                              'shippingdate'=>'2023-06-13',
                              'discordlink'=>'https://discord.gg/',
                              'deleted'=>'0',
                              'verified'=>'1',
                              'rejectreason'=>'0',
                              'interestdone'=>'0',
                              'isfinish'=>'0',
                              'icfail'=>'0',
                      
                              ],

                              [
                                'user_id'=>'3',
                                'product_name'=>'Cherry Notion',
                                'folderpath'=>'img/productseederimg14',
                                'owner'=>'adrian123',
                                'shortdesc'=>'Cherry PBT Dyesub Keycaps.',
                                'product_type'=>'customkeyboard',
                                'productlist'=>'Base Kit',
                                'moq'=>'1',
                                'productstock'=>'10',
                                'productprice'=>'1800000',
                                'startdate'=>'2022-06-13',
                                'enddate'=>'2022-12-13',
                                'enddategb'=>'2023-12-13',
                                'endtime'=>'18:06',
                                'shippingdate'=>'2023-06-13',
                                'discordlink'=>'https://discord.gg/',
                                'deleted'=>'0',
                                'verified'=>'1',
                                'rejectreason'=>'0',
                                'interestdone'=>'0',
                                'isfinish'=>'0',
                                'icfail'=>'0',
                        
                                ],

                                [
                                  'user_id'=>'3',
                                  'product_name'=>'Cherry Milkshake',
                                  'folderpath'=>'img/productseederimg15',
                                  'owner'=>'adrian123',
                                  'shortdesc'=>'Cherry PBT Dyesub Keycaps.',
                                  'product_type'=>'customkeyboard',
                                  'productlist'=>'Base Kit',
                                  'moq'=>'1',
                                  'productstock'=>'10',
                                  'productprice'=>'2200000',
                                  'startdate'=>'2022-06-13',
                                  'enddate'=>'2022-12-13',
                                  'enddategb'=>'2023-12-13',
                                  'endtime'=>'18:06',
                                  'shippingdate'=>'2023-06-13',
                                  'discordlink'=>'https://discord.gg/',
                                  'deleted'=>'0',
                                  'verified'=>'1',
                                  'rejectreason'=>'0',
                                  'interestdone'=>'0',
                                  'isfinish'=>'0',
                                  'icfail'=>'0',
                          
                                  ],

                                  [
                                    'user_id'=>'3',
                                    'product_name'=>'Cherry Sand',
                                    'folderpath'=>'img/productseederimg16',
                                    'owner'=>'adrian123',
                                    'shortdesc'=>'Cherry PBT Dyesub Keycaps.',
                                    'product_type'=>'customkeyboard',
                                    'productlist'=>'Base Kit',
                                    'moq'=>'1',
                                    'productstock'=>'10',
                                    'productprice'=>'2100000',
                                    'startdate'=>'2022-06-13',
                                    'enddate'=>'2022-12-13',
                                    'enddategb'=>'2023-12-13',
                                    'endtime'=>'18:06',
                                    'shippingdate'=>'2023-06-13',
                                    'discordlink'=>'https://discord.gg/',
                                    'deleted'=>'0',
                                    'verified'=>'1',
                                    'rejectreason'=>'0',
                                    'interestdone'=>'0',
                                    'isfinish'=>'0',
                                    'icfail'=>'0',
                            
                                    ],

                                    [
                                      'user_id'=>'3',
                                      'product_name'=>'Cherry Blossom',
                                      'folderpath'=>'img/productseederimg17',
                                      'owner'=>'adrian123',
                                      'shortdesc'=>'Cherry PBT Dyesub Keycaps.',
                                      'product_type'=>'customkeyboard',
                                      'productlist'=>'Base Kit',
                                      'moq'=>'1',
                                      'productstock'=>'10',
                                      'productprice'=>'2200000',
                                      'startdate'=>'2022-06-13',
                                      'enddate'=>'2022-12-13',
                                      'enddategb'=>'2023-12-13',
                                      'endtime'=>'18:06',
                                      'shippingdate'=>'2023-06-13',
                                      'discordlink'=>'https://discord.gg/',
                                      'deleted'=>'0',
                                      'verified'=>'1',
                                      'rejectreason'=>'0',
                                      'interestdone'=>'0',
                                      'isfinish'=>'0',
                                      'icfail'=>'0',
                              
                                      ],

                                      [
                                        'user_id'=>'3',
                                        'product_name'=>'Cherry Heisenberg',
                                        'folderpath'=>'img/productseederimg18',
                                        'owner'=>'adrian123',
                                        'shortdesc'=>'Cherry PBT Dyesub Keycaps.',
                                        'product_type'=>'customkeyboard',
                                        'productlist'=>'Base Kit',
                                        'moq'=>'1',
                                        'productstock'=>'10',
                                        'productprice'=>'1700000',
                                        'startdate'=>'2022-06-13',
                                        'enddate'=>'2022-12-13',
                                        'enddategb'=>'2023-12-13',
                                        'endtime'=>'18:06',
                                        'shippingdate'=>'2023-06-13',
                                        'discordlink'=>'https://discord.gg/',
                                        'deleted'=>'0',
                                        'verified'=>'1',
                                        'rejectreason'=>'0',
                                        'interestdone'=>'0',
                                        'isfinish'=>'0',
                                        'icfail'=>'0',
                                
                                        ],

                                        [
                                          'user_id'=>'3',
                                          'product_name'=>'Cherry Ember',
                                          'folderpath'=>'img/productseederimg19',
                                          'owner'=>'adrian123',
                                          'shortdesc'=>'Cherry PBT Dyesub Keycaps.',
                                          'product_type'=>'customkeyboard',
                                          'productlist'=>'Base Kit',
                                          'moq'=>'1',
                                          'productstock'=>'10',
                                          'productprice'=>'1500000',
                                          'startdate'=>'2022-06-13',
                                          'enddate'=>'2022-12-13',
                                          'enddategb'=>'2023-12-13',
                                          'endtime'=>'18:06',
                                          'shippingdate'=>'2023-06-13',
                                          'discordlink'=>'https://discord.gg/',
                                          'deleted'=>'0',
                                          'verified'=>'1',
                                          'rejectreason'=>'0',
                                          'interestdone'=>'0',
                                          'isfinish'=>'0',
                                          'icfail'=>'0',
                                  
                                          ],

                                          [
                                            'user_id'=>'3',
                                            'product_name'=>'Cherry Charcoal',
                                            'folderpath'=>'img/productseederimg20',
                                            'owner'=>'adrian123',
                                            'shortdesc'=>'Cherry PBT Dyesub Keycaps.',
                                            'product_type'=>'customkeyboard',
                                            'productlist'=>'Base Kit',
                                            'moq'=>'1',
                                            'productstock'=>'10',
                                            'productprice'=>'1900000',
                                            'startdate'=>'2022-06-13',
                                            'enddate'=>'2022-12-13',
                                            'enddategb'=>'2023-12-13',
                                            'endtime'=>'18:06',
                                            'shippingdate'=>'2023-06-13',
                                            'discordlink'=>'https://discord.gg/',
                                            'deleted'=>'0',
                                            'verified'=>'1',
                                            'rejectreason'=>'0',
                                            'interestdone'=>'0',
                                            'isfinish'=>'0',
                                            'icfail'=>'0',
                                    
                                            ],

    ];
    foreach($product as $key=>$value){
        ProductDetail::create($value);
     }

    }
}
